repos:

  - repo: https://github.com/frostming/fix-future-annotations
    rev: b02b4ff7fc10ae0ccabaaf0ec85a185b158fe2b2  # 0.5.0
    hooks:
      - id: fix-future-annotations

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 0ccbb5b7942d83fbcf7cb5e0fd99633efd2351d7  # v0.3.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # v4.6.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first

  - repo: https://github.com/frnhr/pre-commit-nocommit
    rev: dc2021c177b835bc266e423da88d43af6161ffdd  # 0.0.1
    hooks:
      - id: check-nocommit

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 8cd2d4056637e242709fe09f15a36f0b4b682bda  # v1.8.0
    hooks:
      - id: mypy
        exclude: ^(manage_prodselect.py)|(.*/migrations/.*)$
        additional_dependencies: []
