# Generated by Django 5.0.4 on 2024-04-08 22:23

import django.db.models.deletion
from django.db import migrations, models

import backend.apps.users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("selection", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSelectionProxy",
            fields=[],
            options={
                "verbose_name": "User",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", backend.apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="selection",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="selection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="selection.userselectionproxy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="selection",
            unique_together={("user", "product")},
        ),
    ]
