# Generated by Django 5.0.4 on 2024-04-06 23:01

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models

import prodselect.apps.users.models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        ("products", "0001_initial"),
        ("users", "0002_alter_user_email_alter_user_username"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="UserSelectionProxy",
            fields=[],
            options={
                "verbose_name": "User",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", prodselect.apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="selection.userselectionproxy",
                    ),
                ),
            ],
        ),
    ]
