# Generated by Django 5.0.4 on 2024-04-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('user', 'product')},
        ),
    ]
